#include "SiyiCameraSettings.h"

DECLARE_SETTINGGROUP(SiyiCamera, "SiyiCamera")
{
}

DECLARE_SETTINGSFACT(SiyiCameraSettings, enabled)
DECLARE_SETTINGSFACT(SiyiCameraSettings, ipAddress)
DECLARE_SETTINGSFACT(SiyiCameraSettings, port)
DECLARE_SETTINGSFACT(SiyiCameraSettings, secondaryRtspUrl)
DECLARE_SETTINGSFACT(SiyiCameraSettings, aiEnabled)
DECLARE_SETTINGSFACT(SiyiCameraSettings, aiIpAddress)
DECLARE_SETTINGSFACT(SiyiCameraSettings, aiPort)
DECLARE_SETTINGSFACT(SiyiCameraSettings, aiRtspUrl)
DECLARE_SETTINGSFACT(SiyiCameraSettings, fpvRtspUrl)
DECLARE_SETTINGSFACT(SiyiCameraSettings, autoRecordMission)
DECLARE_SETTINGSFACT(SiyiCameraSettings, recordingFileName)
DECLARE_SETTINGSFACT(SiyiCameraSettings, recordingAutoDeleteDays)
DECLARE_SETTINGSFACT(SiyiCameraSettings, recordingAdminOnly)
DECLARE_SETTINGSFACT(SiyiCameraSettings, thermalCorrectionEnabled)
DECLARE_SETTINGSFACT(SiyiCameraSettings, thermalEmissivity)
DECLARE_SETTINGSFACT(SiyiCameraSettings, thermalHumidity)
DECLARE_SETTINGSFACT(SiyiCameraSettings, thermalAmbientTempC)
DECLARE_SETTINGSFACT(SiyiCameraSettings, thermalReflectedTempC)
DECLARE_SETTINGSFACT(SiyiCameraSettings, sendFcDataToGimbal)
DECLARE_SETTINGSFACT(SiyiCameraSettings, fcDataLayout)
DECLARE_SETTINGSFACT(SiyiCameraSettings, crowdModerateCount)
DECLARE_SETTINGSFACT(SiyiCameraSettings, crowdDenseCount)
